### ISSUE TITLE
Deploy to Bluemix button works, but application fails to start

### ISSUE THREAD

**Issue by donbr** [watson-developer-cloud/natural-language-understanding-nodejs#15]
I'm able to run the application locally, but I've been unable to run it successfully on Bluemix.

Errors below are based on using the 'Deploy to Bluemix' button as this is the easiest way to reproduce the issue.

**While Staging, the following error is reported:**

`Native code compile failed`

**Shortly after starting, the application crashes with the following error:**

`Error: Cannot find module 'classnames' from '/home/vcap/app/node_modules/watson-react-components/dist/components'`

**Comment by germanattanasio** [comment]
I think we need to add `classnames` to the package.json.

**Comment by chughts** [comment]
This error is because the package-lock.json file is out of sync with package.json. If you deploy then package-lock.json is used to fetch dependencies, which are the wrong versions, at least for watson-react-components.

https://developer.ibm.com/answers/questions/389154/cannot-find-module-c-lassnames-from-homevcapappnod.html#answer-389737
